### ISSUE TITLE
Report is added to wrong GH workflow

### ISSUE THREAD

**Issue by jkowalleck** [mikepenz/action-junit-report-legacy#34]
Hello @mikepenz 

something seams odd with the reporting: 
reports are attached to the wrong action runs.

## Setup 

Having multiple github actions. Each action uses `action-junit-report` to report junit test results.   
Multiple github actions can run at the same time.

## Expected

Each github action has its junit reporting added to its own run.

## Observed

One github action has all the junit reporting added to its run.
All the other github actions dont have any reported to their runs.

## Example

See my setup: https://github.com/jkowalleck/test_action-junit-report
See the reports: https://github.com/jkowalleck/test_action-junit-report/actions
* A: https://github.com/jkowalleck/test_action-junit-report/actions/runs/437844448
  ![run_A](https://user-images.githubusercontent.com/2765863/102881925-dfa16900-444d-11eb-9067-a277e249c692.png)
* B: https://github.com/jkowalleck/test_action-junit-report/actions/runs/437861885
  ![run_B](https://user-images.githubusercontent.com/2765863/102881937-e7610d80-444d-11eb-8edf-fd3605b4cc15.png)

**Comment by jkowalleck** [comment]
you might wonder, why i have multiple actions, instead of having multiple jobs.  
This is due to the fact that each action has different `path`-constraints to its triggers. One action triggers when any file in directory ``A`` changes,  another action for directory ``B`` -- just like in a monorepo structure.
If in the same commit multiple files in ``A`` and ``B`` change, both actions are triggered at the same time.

**Comment by mikepenz** [comment]
@jkowalleck sadly this is a "bug" of GitHub actions. sometimes it fails to identify the right workflow to use to have results attached to. 

I sadly don't have the reported ticket available right at the moment. but will try to find it again to attach here

**Comment by mikepenz** [comment]
One of the related issues at I could quickly find again: https://github.community/t/github-actions-status-checks-created-on-incorrect-check-suite-id/16685
